version: '3.9'

services:

  db:
    image: postgres
    restart: always
    container_name: PostgreSQL
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: to-do
      PGDATA: /data/postgres
    volumes:
      - ./data/postgres:/data/postgres